export default {
  playerHealth: 0,
  playerArmour: 0,
  playerDamage: 0,
  playerRunic: 0,
  playerMana: 0,
  playerHitChanceModifier: 0,
  playerLevel: 0,
  playerClass: 'null',
  playerMaxMana: 100,
  playerGraphic: '/res/player/wizard/wizard-1.png',
  playerWeapon: '',
  currentMonster: null,
  monsterHealth: 0,
  monsterArmour: 0,
  monsterDamage: 0,
  monsterRage: 0,
  monsterName: null,
  gold: 100,
}